# Generated by Django 3.2.13 on 2022-04-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcapyWebhook',
            fields=[
                ('type', models.CharField(choices=[('null', 'Null'), ('connections', 'Connections'), ('basicmessages', 'Basicmessages'), ('forward', 'Forward'), ('issue_credential', 'Issuecredential'), ('present_proof', 'Presentproof')], default='null', max_length=30)),
                ('received_at', models.DateTimeField(primary_key=True, serialize=False)),
                ('content', models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('connection_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('their_label', models.CharField(default='Max', max_length=100)),
                ('created_at', models.DateTimeField(default='2022-04-01T13:06:15.833333Z')),
                ('updated_at', models.DateTimeField(default='2022-04-01T13:06:15.833333Z')),
                ('their_role', models.CharField(choices=[('null', 'Null'), ('invitee', 'Invitee'), ('requester', 'Requester'), ('inviter', 'Inviter'), ('responder', 'Responder')], default='null', max_length=10)),
                ('state', models.CharField(choices=[('start', 'Start'), ('invitation', 'Invitation'), ('request', 'Request'), ('response', 'Response'), ('completed', 'Completed'), ('active', 'Active'), ('abandoned', 'Abandoned')], default='start', max_length=10)),
                ('accept', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('proposal_sent', 'Proposal Sent'), ('proposal_received', 'Proposal Received'), ('offer_sent', 'Offer Sent'), ('offer_received', 'Offer Received'), ('request_sent', 'Request Sent'), ('request_received', 'Request Received'), ('issued', 'Issued'), ('credential_received', 'Credential Received'), ('credential_acked', 'Credential Acked')], max_length=30)),
                ('credential_proposal_dict', models.JSONField()),
                ('attributes', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField()),
                ('connection_id', models.CharField(max_length=100)),
                ('credential_definition_id', models.CharField(max_length=100)),
                ('schema_id', models.CharField(max_length=100)),
                ('credential_exchange_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('schema_name', models.CharField(default='null', max_length=30)),
                ('schema_version', models.CharField(default='1.0', max_length=4)),
                ('credential_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PresentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_request_name', models.CharField(max_length=50)),
                ('presentation_exchange_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('request_received', 'Request Received'), ('proposal_sent', 'Proposal Sent'), ('presentation_sent', 'Presentation Sent'), ('presentation_acked', 'Presentation Acked'), ('reject_sent', 'Reject Sent'), ('done', 'Done')], max_length=30)),
                ('presentation_request', models.JSONField()),
                ('requested_attributes', models.JSONField()),
            ],
        ),
    ]
