# Generated by Django 3.2.13 on 2022-04-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acapywebhook',
            name='type',
            field=models.CharField(choices=[('null', 'Null'), ('connections', 'Connections'), ('basicmessages', 'Basicmessages'), ('forward', 'Forward'), ('issue_credential', 'Issuecredential'), ('present_proof', 'Presentproof'), ('revocation_notification', 'Revocationnotification')], default='null', max_length=30),
        ),
    ]
