# Generated by Django 3.2.13 on 2022-04-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_wallet', '0002_alter_acapywebhook_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentproof',
            name='did',
            field=models.CharField(default='did:sov', max_length=50),
        ),
    ]
