# Generated by Django 3.2.13 on 2022-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_wallet', '0003_presentproof_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='thread_id',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
