# Generated by Django 3.2.13 on 2022-04-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aries_wallet', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
