# Generated by Django 3.2.13 on 2022-05-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_wallet', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentproof',
            name='connection_id',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
