# Generated by Django 3.2.13 on 2022-05-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_wallet', '0007_presentproof_connection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentproof',
            name='requested_predicates',
            field=models.JSONField(default='null'),
        ),
        migrations.AddField(
            model_name='presentproof',
            name='self_attested',
            field=models.JSONField(default='null'),
        ),
    ]
