# Generated by Django 3.2.13 on 2022-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_wallet', '0008_auto_20220508_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentproof',
            name='requested_predicates',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='presentproof',
            name='self_attested',
            field=models.JSONField(),
        ),
    ]
