# Generated by Django 3.2.13 on 2022-05-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_wallet', '0009_auto_20220508_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='predicates',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='presentproof',
            name='presentation_request',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='presentproof',
            name='requested_attributes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='presentproof',
            name='requested_predicates',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='presentproof',
            name='self_attested',
            field=models.JSONField(default=dict),
        ),
    ]
