# Generated by Django 3.2.13 on 2022-05-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aries_wallet', '0010_auto_20220508_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='predicates',
        ),
    ]
