# Generated by Django 3.2.13 on 2022-05-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aries_wallet', '0011_remove_credential_predicates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentproof',
            name='self_attested',
        ),
    ]
