# Generated by Django 3.2.13 on 2022-06-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aries_wallet', '0012_remove_presentproof_self_attested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='their_label',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
